# Generated by Django 5.2.6 on 2025-09-20 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('emailVerificado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, db_index=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d+$', 'El teléfono debe contener solo números y puede iniciar con +.')])),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'La cédula solo puede contener números.'), django.core.validators.MinLengthValidator(6, 'La cédula debe tener al menos 6 dígitos.')])),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], db_index=True, default='cliente', max_length=20)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('googleId', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('fotoPerfil', models.URLField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('creadoEn', models.DateTimeField(auto_now_add=True)),
                ('actualizadoEn', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-creadoEn'],
                'indexes': [models.Index(fields=['rol'], name='usuarios_us_rol_1f6a22_idx'), models.Index(fields=['emailVerificado'], name='usuarios_us_emailVe_76f09d_idx')],
            },
        ),
    ]
